name: Build stats
on:
  pull_request:
    types: synchronize
env:
  BUILD_TYPE: Release
  FOAM_INST_DIR: /root/OpenFOAM
  WM_PROJECT: OpenFOAM
  WM_OPTIONS: linux64GccDPInt32Opt
  WM_COMPILER_TYPE: system
  WM_COMPILER: Gcc
  WM_PRECISION_OPTION: DP
  WM_LABEL_SIZE: 32
  WM_COMPILE_OPTION: Opt
  WM_OSTYPE: POSIX
  WM_ARCH: linux64
  WM_ARCH_OPTION: 64
  WM_LINK_LANGUAGE: c++
  WM_LABEL_OPTION:  Int32
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

jobs:
  generate_job_doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git clone https://github.com/hpsim/OBR.git -b feat/archive_views
        cd OBR
        python -m pip install . 
        python -m pip install matplotlib tabulate
        cd ..

    - name: Run obr script
      run: |
        cd LidDrivenCavity3D
        obr apply --file ../scripts/postProcessLogs.py --campaign ogl_170

    - name: Run obr script
      run: |
        cd LidDrivenCavity3D
        echo "overview\n\n" > overview.md
        obr status --sort_by nCells,nProcs,executor,preconditioner --extra ClockTime --hide jobid  --export_to markdown >> overview.md

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: LidDrivenCavity3D/overview.md

    #     cd ../WindsorBody
    #     obr run -o apply ../scripts/postProcessLogs.py
    #
    # - name: Commit updated job_documents
    #   run: |
    #     cd LidDrivenCavity3D
    #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
    #     git config --local user.name "github-actions[bot]"
    #     git add workspace/*/signac_job_document.json
    #     git commit --allow-empty -m "update signac_job_document"
    #
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     branch: ${{ github.head_ref }}
    #     force: True
