name: Build stats
on:
  pull_request:
    types: synchronize
env:
  BUILD_TYPE: Release
  FOAM_INST_DIR: /root/OpenFOAM
  WM_PROJECT: OpenFOAM
  WM_OPTIONS: linux64GccDPInt32Opt
  WM_COMPILER_TYPE: system
  WM_COMPILER: Gcc
  WM_PRECISION_OPTION: DP
  WM_LABEL_SIZE: 32
  WM_COMPILE_OPTION: Opt
  WM_OSTYPE: POSIX
  WM_ARCH: linux64
  WM_ARCH_OPTION: 64
  WM_LINK_LANGUAGE: c++
  WM_LABEL_OPTION:  Int32
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

jobs:
  generate_job_doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git clone https://github.com/hpsim/OBR.git -b feat/archive_views
        cd OBR
        python -m pip install . 
        python -m pip install matplotlib tabulate seaborn
        python -m pip install pyparsing --upgrade
        cd ..

    - name: Extract branch name
      shell: bash
      run: echo "CAMPAIGN=$(dirname ${GITHUB_HEAD_REF})" >> $GITHUB_ENV

    - name: Run obr script
      run: |
        cd LidDrivenCavity3D
        obr apply --file ../scripts/postProcessLogs.py --campaign ${{env.CAMPAIGN}}

    - name: Run obr script
      run: |
        cd LidDrivenCavity3D
        echo "# Results Overview " > overview.md
        echo "## Unpreconditioned" >> overview.md
        obr status --filter preconditioner==none --sort_by nCells,nProcs,executor --extra TimeStep,SolveP,MomentumPredictor,PISOStep --hide jobid,view  --export_to markdown >> overview.md
        echo "## Preconditioned" >> overview.md
        obr status --filter preconditioner!=none --sort_by nCells,nProcs,executor,preconditioner --extra TimeStep,SolveP,MomentumPredictor,PISOStep --hide jobid,view  --export_to markdown >> overview.md
        mkdir -p postProcessing/${{env.CAMPAIGN}}
        obr status --sort_by nCells,nProcs,executor,preconditioner --extra TimeStep,SolveP,MomentumPredictor,PISOStep,Host,solver_p --export_to json > postProcessing/${{env.CAMPAIGN}}/results.json

    - name: Create Plots
      run: |
        cd LidDrivenCavity3D/
        python3 assets/plot.py

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: LidDrivenCavity3D/overview.md

    - name: Commit updated job_documents
      run: |
          cd LidDrivenCavity3D
          git config --global user.name "Continuous Integration Bot"
          git config --global user.email "go@hpsim.de"
          git add postProcessing/${{env.CAMPAIGN}}
          git commit --allow-empty -m "add campaign results"

    - name: Upload plots
      uses: edunad/actions-image@v2.0.0
      with:
          path: ./LidDrivenCavity3D/postProcessing/${{env.CAMPAIGN}}/*.png
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
        force: True
