name: Build OpenFOAM (ESI|FOUNDATION)
on:
  push:
  pull_request:
    types: synchronize
  schedule:
    - cron: "* * * * 0"
env:
  BUILD_TYPE: Release
  FOAM_INST_DIR: /root/OpenFOAM
  WM_PROJECT: OpenFOAM
  WM_OPTIONS: linux64GccDPInt32Opt
  WM_COMPILER_TYPE: system
  WM_COMPILER: Gcc
  WM_PRECISION_OPTION: DP
  WM_LABEL_SIZE: 32
  WM_COMPILE_OPTION: Opt
  WM_OSTYPE: POSIX
  WM_ARCH: linux64
  WM_ARCH_OPTION: 64
  WM_LINK_LANGUAGE: c++
  WM_LABEL_OPTION:  Int32
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

jobs:
  generate_job_doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git clone https://github.com/hpsim/OBR.git
        cd OBR
        python -m pip install . 
        cd ..
        git clone https://github.com/exasim-project/exasim_plot_helpers.git
        cd exasim_plot_helpers
        python -m pip install . 
        python -m pip install matplotlib
        cd ..

    - name: Run obr script
      run: | 
        cd LidDrivenCavity3D
        obr run -o apply -a --args ../scripts/postProcessLogs.py

    - name: Commit updated job_documents
      run: |
        cd LidDrivenCavity3D
        git add workspace/*/signac_job_document.json
        git commit -m "update signac_job_document"
        git push origin

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
